### ISSUE TITLE
Increase speed of method new_distance

### ISSUE THREAD

**Issue by marie3003** [datascience-mobi/2021-topic-04-team-04#29]
Wir suchen nach einer Möglichkeit die Methode new_distance in seeded_region_growing_test.py zu vektorisieren, um for Schleifen zu vermeiden. In der Methode werden alle Pixel der Liste von direkten Nachbarn von Regionen (Ne) betrachtet und deren Distanzen zu den Intensitätswerten ihrer angrenzenden Regionen berechnet. Die minimale Distanz wird in einem Array mit der Form des Ursprungspixels gespeichert. Dieses Array kann anschließend verwendet werden, um den Pixel zu finden, der als nächstes einer Region zugeordnet werden muss.
Unser Problem ist, dass wir von allen Pixeln in der Nachbarnliste Ne deren Distanz zu allen ihren Nachbarregionen (maximal 4) berechnen müssen. Dabei betrachten wir jeweils die 4 Nachbarn eines Pixels aus Ne und prüfen ob dieser innerhalb des Rands liegt und schon zugeordnet ist. So erhalten wir maximal vier angrenzende Regionen, zu denen wir die Distanzen berechnen und die minimale Distanz auswählen. Insgesamt betrachten wir nur Pixel in Ne, die an die veränderte Region angrenzen, um Zeit zu sparen.
Bis jetzt habe ich keine Idee, wie dieser Prozess vektorisiert werden kann.

Die Methode wird unter main ausgeführt, wenn die Methode region_growing aufgerufen wird.

Vielen Dank fürs Anschauen!

**Comment by npeschke** [comment]
Hey, I'm sorry but the function is a bit too complex and convoluted at the moment for me to understand it.
You can improve the readability by:
- adding a docstring with explanations for the parameters of the function
    - it is also helpful to give details about the data types there e.g. if `Ne` is a list of tuples of (x,y) coordinates of neighbors
- rename variables like `Ne` to something describing the data and maybe its intention like `unassigned_neighbors`
- in loops use `i`, `j` and `k` only if you are actually dealing with numerical indices
    - in the case of `for i in Ne` it could be e.g. `for neighbor_to_assign in unassigned_neighbors`
- use precise function names e.g. `add_neighbors(img, p)` which implies some numerical addition or at least an append operation on a list. Instead you could name it `get_neighbors(img, coordinates)`.
- Before you start refactoring everything, you should remove duplicates in the code and adhere to the single responsibility principle. Otherwise it will become very hard to distinguish between which version of a function like `find_neighbors` `find_neighbors2` or their equivalents in files other than `seeded_region_growing_test.py`

**Comment by npeschke** [comment]
I've noticed that you are using a jupyter notebook to run the code.
There is some jupyter magic called autoreload (`%autoreload 2` [link to docs](https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html)) which automatically reloads all modules used in a cell before you run the cell.

This means you can have the functions defined once in a module (plain .py file) and run the function from the jupyter notebook. If you want to debug the function, you edit it in the module and those changes get automatically reloaded by the autoreload magic in the jupyter notebook when you run the cell again.

**Comment by marie3003** [comment]
Hey Nicolas,

we reformated our methods. Can you look over the method new_distance in seeded_region_growing.py (folder functions) again?

Thank's a lot!!

**Comment by npeschke** [comment]
Great work on refactoring your package, it is now much easier to understand!

I've profiled the script on my side and did not find an immediate speedup for the most time consuming function `calculate_distance` but as it is called millions of times, maybe trying to reduce the number of calls to it might be the way to go.
This boils down to finding a data structure for the neighbor distances with which you can access them efficiently without the constant need of array lookups. One such way might be to use a pandas DataFrame to track the distances together with the coordinates and the region number. Alternatively, you could also think about writing your own classes to track regions etc.

You could also think about possibilities to calculate stuff in parallel. This goes hand in hand with finding a more suitable data structure.
